# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/nikod/Documents/uni/chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/nikod/Documents/uni/chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/nikod/Documents/uni/chess/CMakeFiles /mnt/c/Users/nikod/Documents/uni/chess//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/nikod/Documents/uni/chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /mnt/c/Users/nikod/Documents/uni/chess/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

nnue_net_data.o: nnue_net_data.cpp.o
.PHONY : nnue_net_data.o

# target to build an object file
nnue_net_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/nnue_net_data.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/nnue_net_data.cpp.o
.PHONY : nnue_net_data.cpp.o

nnue_net_data.i: nnue_net_data.cpp.i
.PHONY : nnue_net_data.i

# target to preprocess a source file
nnue_net_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/nnue_net_data.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/nnue_net_data.cpp.i
.PHONY : nnue_net_data.cpp.i

nnue_net_data.s: nnue_net_data.cpp.s
.PHONY : nnue_net_data.s

# target to generate assembly for a file
nnue_net_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/nnue_net_data.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/nnue_net_data.cpp.s
.PHONY : nnue_net_data.cpp.s

src/attacks.o: src/attacks.cpp.o
.PHONY : src/attacks.o

# target to build an object file
src/attacks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/attacks.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/attacks.cpp.o
.PHONY : src/attacks.cpp.o

src/attacks.i: src/attacks.cpp.i
.PHONY : src/attacks.i

# target to preprocess a source file
src/attacks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/attacks.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/attacks.cpp.i
.PHONY : src/attacks.cpp.i

src/attacks.s: src/attacks.cpp.s
.PHONY : src/attacks.s

# target to generate assembly for a file
src/attacks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/attacks.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/attacks.cpp.s
.PHONY : src/attacks.cpp.s

src/bitboard.o: src/bitboard.cpp.o
.PHONY : src/bitboard.o

# target to build an object file
src/bitboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/bitboard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/bitboard.cpp.o
.PHONY : src/bitboard.cpp.o

src/bitboard.i: src/bitboard.cpp.i
.PHONY : src/bitboard.i

# target to preprocess a source file
src/bitboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/bitboard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/bitboard.cpp.i
.PHONY : src/bitboard.cpp.i

src/bitboard.s: src/bitboard.cpp.s
.PHONY : src/bitboard.s

# target to generate assembly for a file
src/bitboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/bitboard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/bitboard.cpp.s
.PHONY : src/bitboard.cpp.s

src/crash.o: src/crash.cpp.o
.PHONY : src/crash.o

# target to build an object file
src/crash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/crash.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/crash.cpp.o
.PHONY : src/crash.cpp.o

src/crash.i: src/crash.cpp.i
.PHONY : src/crash.i

# target to preprocess a source file
src/crash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/crash.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/crash.cpp.i
.PHONY : src/crash.cpp.i

src/crash.s: src/crash.cpp.s
.PHONY : src/crash.s

# target to generate assembly for a file
src/crash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/crash.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/crash.cpp.s
.PHONY : src/crash.cpp.s

src/datagen.o: src/datagen.cpp.o
.PHONY : src/datagen.o

# target to build an object file
src/datagen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/datagen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/datagen.cpp.o
.PHONY : src/datagen.cpp.o

src/datagen.i: src/datagen.cpp.i
.PHONY : src/datagen.i

# target to preprocess a source file
src/datagen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/datagen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/datagen.cpp.i
.PHONY : src/datagen.cpp.i

src/datagen.s: src/datagen.cpp.s
.PHONY : src/datagen.s

# target to generate assembly for a file
src/datagen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/datagen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/datagen.cpp.s
.PHONY : src/datagen.cpp.s

src/eval.o: src/eval.cpp.o
.PHONY : src/eval.o

# target to build an object file
src/eval.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/eval.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/eval.cpp.o
.PHONY : src/eval.cpp.o

src/eval.i: src/eval.cpp.i
.PHONY : src/eval.i

# target to preprocess a source file
src/eval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/eval.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/eval.cpp.i
.PHONY : src/eval.cpp.i

src/eval.s: src/eval.cpp.s
.PHONY : src/eval.s

# target to generate assembly for a file
src/eval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/eval.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/eval.cpp.s
.PHONY : src/eval.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/movegen.o: src/movegen.cpp.o
.PHONY : src/movegen.o

# target to build an object file
src/movegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/movegen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/movegen.cpp.o
.PHONY : src/movegen.cpp.o

src/movegen.i: src/movegen.cpp.i
.PHONY : src/movegen.i

# target to preprocess a source file
src/movegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/movegen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/movegen.cpp.i
.PHONY : src/movegen.cpp.i

src/movegen.s: src/movegen.cpp.s
.PHONY : src/movegen.s

# target to generate assembly for a file
src/movegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/movegen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/movegen.cpp.s
.PHONY : src/movegen.cpp.s

src/nnue.o: src/nnue.cpp.o
.PHONY : src/nnue.o

# target to build an object file
src/nnue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/nnue.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/nnue.cpp.o
.PHONY : src/nnue.cpp.o

src/nnue.i: src/nnue.cpp.i
.PHONY : src/nnue.i

# target to preprocess a source file
src/nnue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/nnue.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/nnue.cpp.i
.PHONY : src/nnue.cpp.i

src/nnue.s: src/nnue.cpp.s
.PHONY : src/nnue.s

# target to generate assembly for a file
src/nnue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/nnue.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/nnue.cpp.s
.PHONY : src/nnue.cpp.s

src/perft.o: src/perft.cpp.o
.PHONY : src/perft.o

# target to build an object file
src/perft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/perft.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/perft.cpp.o
.PHONY : src/perft.cpp.o

src/perft.i: src/perft.cpp.i
.PHONY : src/perft.i

# target to preprocess a source file
src/perft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/perft.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/perft.cpp.i
.PHONY : src/perft.cpp.i

src/perft.s: src/perft.cpp.s
.PHONY : src/perft.s

# target to generate assembly for a file
src/perft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/perft.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/perft.cpp.s
.PHONY : src/perft.cpp.s

src/position.o: src/position.cpp.o
.PHONY : src/position.o

# target to build an object file
src/position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/position.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/position.cpp.o
.PHONY : src/position.cpp.o

src/position.i: src/position.cpp.i
.PHONY : src/position.i

# target to preprocess a source file
src/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/position.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/position.cpp.i
.PHONY : src/position.cpp.i

src/position.s: src/position.cpp.s
.PHONY : src/position.s

# target to generate assembly for a file
src/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/position.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/position.cpp.s
.PHONY : src/position.cpp.s

src/search.o: src/search.cpp.o
.PHONY : src/search.o

# target to build an object file
src/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/search.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/search.cpp.o
.PHONY : src/search.cpp.o

src/search.i: src/search.cpp.i
.PHONY : src/search.i

# target to preprocess a source file
src/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/search.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/search.cpp.i
.PHONY : src/search.cpp.i

src/search.s: src/search.cpp.s
.PHONY : src/search.s

# target to generate assembly for a file
src/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/search.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/search.cpp.s
.PHONY : src/search.cpp.s

src/see.o: src/see.cpp.o
.PHONY : src/see.o

# target to build an object file
src/see.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/see.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/see.cpp.o
.PHONY : src/see.cpp.o

src/see.i: src/see.cpp.i
.PHONY : src/see.i

# target to preprocess a source file
src/see.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/see.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/see.cpp.i
.PHONY : src/see.cpp.i

src/see.s: src/see.cpp.s
.PHONY : src/see.s

# target to generate assembly for a file
src/see.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/see.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/see.cpp.s
.PHONY : src/see.cpp.s

src/syzygy.o: src/syzygy.cpp.o
.PHONY : src/syzygy.o

# target to build an object file
src/syzygy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/syzygy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/syzygy.cpp.o
.PHONY : src/syzygy.cpp.o

src/syzygy.i: src/syzygy.cpp.i
.PHONY : src/syzygy.i

# target to preprocess a source file
src/syzygy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/syzygy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/syzygy.cpp.i
.PHONY : src/syzygy.cpp.i

src/syzygy.s: src/syzygy.cpp.s
.PHONY : src/syzygy.s

# target to generate assembly for a file
src/syzygy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/syzygy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/syzygy.cpp.s
.PHONY : src/syzygy.cpp.s

src/timeman.o: src/timeman.cpp.o
.PHONY : src/timeman.o

# target to build an object file
src/timeman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/timeman.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/timeman.cpp.o
.PHONY : src/timeman.cpp.o

src/timeman.i: src/timeman.cpp.i
.PHONY : src/timeman.i

# target to preprocess a source file
src/timeman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/timeman.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/timeman.cpp.i
.PHONY : src/timeman.cpp.i

src/timeman.s: src/timeman.cpp.s
.PHONY : src/timeman.s

# target to generate assembly for a file
src/timeman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/timeman.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/timeman.cpp.s
.PHONY : src/timeman.cpp.s

src/tt.o: src/tt.cpp.o
.PHONY : src/tt.o

# target to build an object file
src/tt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/tt.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/tt.cpp.o
.PHONY : src/tt.cpp.o

src/tt.i: src/tt.cpp.i
.PHONY : src/tt.i

# target to preprocess a source file
src/tt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/tt.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/tt.cpp.i
.PHONY : src/tt.cpp.i

src/tt.s: src/tt.cpp.s
.PHONY : src/tt.s

# target to generate assembly for a file
src/tt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/tt.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/tt.cpp.s
.PHONY : src/tt.cpp.s

src/tune.o: src/tune.cpp.o
.PHONY : src/tune.o

# target to build an object file
src/tune.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/tune.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/tune.cpp.o
.PHONY : src/tune.cpp.o

src/tune.i: src/tune.cpp.i
.PHONY : src/tune.i

# target to preprocess a source file
src/tune.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/tune.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/tune.cpp.i
.PHONY : src/tune.cpp.i

src/tune.s: src/tune.cpp.s
.PHONY : src/tune.s

# target to generate assembly for a file
src/tune.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/tune.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/tune.cpp.s
.PHONY : src/tune.cpp.s

src/uci.o: src/uci.cpp.o
.PHONY : src/uci.o

# target to build an object file
src/uci.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/uci.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/uci.cpp.o
.PHONY : src/uci.cpp.o

src/uci.i: src/uci.cpp.i
.PHONY : src/uci.i

# target to preprocess a source file
src/uci.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/uci.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/uci.cpp.i
.PHONY : src/uci.cpp.i

src/uci.s: src/uci.cpp.s
.PHONY : src/uci.s

# target to generate assembly for a file
src/uci.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/uci.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/uci.cpp.s
.PHONY : src/uci.cpp.s

src/zobrist.o: src/zobrist.cpp.o
.PHONY : src/zobrist.o

# target to build an object file
src/zobrist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/zobrist.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/zobrist.cpp.o
.PHONY : src/zobrist.cpp.o

src/zobrist.i: src/zobrist.cpp.i
.PHONY : src/zobrist.i

# target to preprocess a source file
src/zobrist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/zobrist.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/zobrist.cpp.i
.PHONY : src/zobrist.cpp.i

src/zobrist.s: src/zobrist.cpp.s
.PHONY : src/zobrist.s

# target to generate assembly for a file
src/zobrist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/zobrist.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/zobrist.cpp.s
.PHONY : src/zobrist.cpp.s

tests/test_attacks.o: tests/test_attacks.cpp.o
.PHONY : tests/test_attacks.o

# target to build an object file
tests/test_attacks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_attacks.cpp.o
.PHONY : tests/test_attacks.cpp.o

tests/test_attacks.i: tests/test_attacks.cpp.i
.PHONY : tests/test_attacks.i

# target to preprocess a source file
tests/test_attacks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_attacks.cpp.i
.PHONY : tests/test_attacks.cpp.i

tests/test_attacks.s: tests/test_attacks.cpp.s
.PHONY : tests/test_attacks.s

# target to generate assembly for a file
tests/test_attacks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_attacks.cpp.s
.PHONY : tests/test_attacks.cpp.s

tests/test_bitboard.o: tests/test_bitboard.cpp.o
.PHONY : tests/test_bitboard.o

# target to build an object file
tests/test_bitboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_bitboard.cpp.o
.PHONY : tests/test_bitboard.cpp.o

tests/test_bitboard.i: tests/test_bitboard.cpp.i
.PHONY : tests/test_bitboard.i

# target to preprocess a source file
tests/test_bitboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_bitboard.cpp.i
.PHONY : tests/test_bitboard.cpp.i

tests/test_bitboard.s: tests/test_bitboard.cpp.s
.PHONY : tests/test_bitboard.s

# target to generate assembly for a file
tests/test_bitboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_bitboard.cpp.s
.PHONY : tests/test_bitboard.cpp.s

tests/test_draw.o: tests/test_draw.cpp.o
.PHONY : tests/test_draw.o

# target to build an object file
tests/test_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_draw.cpp.o
.PHONY : tests/test_draw.cpp.o

tests/test_draw.i: tests/test_draw.cpp.i
.PHONY : tests/test_draw.i

# target to preprocess a source file
tests/test_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_draw.cpp.i
.PHONY : tests/test_draw.cpp.i

tests/test_draw.s: tests/test_draw.cpp.s
.PHONY : tests/test_draw.s

# target to generate assembly for a file
tests/test_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_draw.cpp.s
.PHONY : tests/test_draw.cpp.s

tests/test_eval.o: tests/test_eval.cpp.o
.PHONY : tests/test_eval.o

# target to build an object file
tests/test_eval.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_eval.cpp.o
.PHONY : tests/test_eval.cpp.o

tests/test_eval.i: tests/test_eval.cpp.i
.PHONY : tests/test_eval.i

# target to preprocess a source file
tests/test_eval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_eval.cpp.i
.PHONY : tests/test_eval.cpp.i

tests/test_eval.s: tests/test_eval.cpp.s
.PHONY : tests/test_eval.s

# target to generate assembly for a file
tests/test_eval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_eval.cpp.s
.PHONY : tests/test_eval.cpp.s

tests/test_magic.o: tests/test_magic.cpp.o
.PHONY : tests/test_magic.o

# target to build an object file
tests/test_magic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_magic.cpp.o
.PHONY : tests/test_magic.cpp.o

tests/test_magic.i: tests/test_magic.cpp.i
.PHONY : tests/test_magic.i

# target to preprocess a source file
tests/test_magic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_magic.cpp.i
.PHONY : tests/test_magic.cpp.i

tests/test_magic.s: tests/test_magic.cpp.s
.PHONY : tests/test_magic.s

# target to generate assembly for a file
tests/test_magic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_magic.cpp.s
.PHONY : tests/test_magic.cpp.s

tests/test_main.o: tests/test_main.cpp.o
.PHONY : tests/test_main.o

# target to build an object file
tests/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_main.cpp.o
.PHONY : tests/test_main.cpp.o

tests/test_main.i: tests/test_main.cpp.i
.PHONY : tests/test_main.i

# target to preprocess a source file
tests/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_main.cpp.i
.PHONY : tests/test_main.cpp.i

tests/test_main.s: tests/test_main.cpp.s
.PHONY : tests/test_main.s

# target to generate assembly for a file
tests/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_main.cpp.s
.PHONY : tests/test_main.cpp.s

tests/test_movegen.o: tests/test_movegen.cpp.o
.PHONY : tests/test_movegen.o

# target to build an object file
tests/test_movegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_movegen.cpp.o
.PHONY : tests/test_movegen.cpp.o

tests/test_movegen.i: tests/test_movegen.cpp.i
.PHONY : tests/test_movegen.i

# target to preprocess a source file
tests/test_movegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_movegen.cpp.i
.PHONY : tests/test_movegen.cpp.i

tests/test_movegen.s: tests/test_movegen.cpp.s
.PHONY : tests/test_movegen.s

# target to generate assembly for a file
tests/test_movegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_movegen.cpp.s
.PHONY : tests/test_movegen.cpp.s

tests/test_nnue.o: tests/test_nnue.cpp.o
.PHONY : tests/test_nnue.o

# target to build an object file
tests/test_nnue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_nnue.cpp.o
.PHONY : tests/test_nnue.cpp.o

tests/test_nnue.i: tests/test_nnue.cpp.i
.PHONY : tests/test_nnue.i

# target to preprocess a source file
tests/test_nnue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_nnue.cpp.i
.PHONY : tests/test_nnue.cpp.i

tests/test_nnue.s: tests/test_nnue.cpp.s
.PHONY : tests/test_nnue.s

# target to generate assembly for a file
tests/test_nnue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_nnue.cpp.s
.PHONY : tests/test_nnue.cpp.s

tests/test_perft.o: tests/test_perft.cpp.o
.PHONY : tests/test_perft.o

# target to build an object file
tests/test_perft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_perft.cpp.o
.PHONY : tests/test_perft.cpp.o

tests/test_perft.i: tests/test_perft.cpp.i
.PHONY : tests/test_perft.i

# target to preprocess a source file
tests/test_perft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_perft.cpp.i
.PHONY : tests/test_perft.cpp.i

tests/test_perft.s: tests/test_perft.cpp.s
.PHONY : tests/test_perft.s

# target to generate assembly for a file
tests/test_perft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_perft.cpp.s
.PHONY : tests/test_perft.cpp.s

tests/test_position.o: tests/test_position.cpp.o
.PHONY : tests/test_position.o

# target to build an object file
tests/test_position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_position.cpp.o
.PHONY : tests/test_position.cpp.o

tests/test_position.i: tests/test_position.cpp.i
.PHONY : tests/test_position.i

# target to preprocess a source file
tests/test_position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_position.cpp.i
.PHONY : tests/test_position.cpp.i

tests/test_position.s: tests/test_position.cpp.s
.PHONY : tests/test_position.s

# target to generate assembly for a file
tests/test_position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_position.cpp.s
.PHONY : tests/test_position.cpp.s

tests/test_search.o: tests/test_search.cpp.o
.PHONY : tests/test_search.o

# target to build an object file
tests/test_search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_search.cpp.o
.PHONY : tests/test_search.cpp.o

tests/test_search.i: tests/test_search.cpp.i
.PHONY : tests/test_search.i

# target to preprocess a source file
tests/test_search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_search.cpp.i
.PHONY : tests/test_search.cpp.i

tests/test_search.s: tests/test_search.cpp.s
.PHONY : tests/test_search.s

# target to generate assembly for a file
tests/test_search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_search.cpp.s
.PHONY : tests/test_search.cpp.s

tests/test_see.o: tests/test_see.cpp.o
.PHONY : tests/test_see.o

# target to build an object file
tests/test_see.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_see.cpp.o
.PHONY : tests/test_see.cpp.o

tests/test_see.i: tests/test_see.cpp.i
.PHONY : tests/test_see.i

# target to preprocess a source file
tests/test_see.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_see.cpp.i
.PHONY : tests/test_see.cpp.i

tests/test_see.s: tests/test_see.cpp.s
.PHONY : tests/test_see.s

# target to generate assembly for a file
tests/test_see.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_see.cpp.s
.PHONY : tests/test_see.cpp.s

tests/test_syzygy.o: tests/test_syzygy.cpp.o
.PHONY : tests/test_syzygy.o

# target to build an object file
tests/test_syzygy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_syzygy.cpp.o
.PHONY : tests/test_syzygy.cpp.o

tests/test_syzygy.i: tests/test_syzygy.cpp.i
.PHONY : tests/test_syzygy.i

# target to preprocess a source file
tests/test_syzygy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_syzygy.cpp.i
.PHONY : tests/test_syzygy.cpp.i

tests/test_syzygy.s: tests/test_syzygy.cpp.s
.PHONY : tests/test_syzygy.s

# target to generate assembly for a file
tests/test_syzygy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_syzygy.cpp.s
.PHONY : tests/test_syzygy.cpp.s

tests/test_timeman.o: tests/test_timeman.cpp.o
.PHONY : tests/test_timeman.o

# target to build an object file
tests/test_timeman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_timeman.cpp.o
.PHONY : tests/test_timeman.cpp.o

tests/test_timeman.i: tests/test_timeman.cpp.i
.PHONY : tests/test_timeman.i

# target to preprocess a source file
tests/test_timeman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_timeman.cpp.i
.PHONY : tests/test_timeman.cpp.i

tests/test_timeman.s: tests/test_timeman.cpp.s
.PHONY : tests/test_timeman.s

# target to generate assembly for a file
tests/test_timeman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_timeman.cpp.s
.PHONY : tests/test_timeman.cpp.s

tests/test_tt.o: tests/test_tt.cpp.o
.PHONY : tests/test_tt.o

# target to build an object file
tests/test_tt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_tt.cpp.o
.PHONY : tests/test_tt.cpp.o

tests/test_tt.i: tests/test_tt.cpp.i
.PHONY : tests/test_tt.i

# target to preprocess a source file
tests/test_tt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_tt.cpp.i
.PHONY : tests/test_tt.cpp.i

tests/test_tt.s: tests/test_tt.cpp.s
.PHONY : tests/test_tt.s

# target to generate assembly for a file
tests/test_tt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_tt.cpp.s
.PHONY : tests/test_tt.cpp.s

tests/test_types.o: tests/test_types.cpp.o
.PHONY : tests/test_types.o

# target to build an object file
tests/test_types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_types.cpp.o
.PHONY : tests/test_types.cpp.o

tests/test_types.i: tests/test_types.cpp.i
.PHONY : tests/test_types.i

# target to preprocess a source file
tests/test_types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_types.cpp.i
.PHONY : tests/test_types.cpp.i

tests/test_types.s: tests/test_types.cpp.s
.PHONY : tests/test_types.s

# target to generate assembly for a file
tests/test_types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_types.cpp.s
.PHONY : tests/test_types.cpp.s

tests/test_uci.o: tests/test_uci.cpp.o
.PHONY : tests/test_uci.o

# target to build an object file
tests/test_uci.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_uci.cpp.o
.PHONY : tests/test_uci.cpp.o

tests/test_uci.i: tests/test_uci.cpp.i
.PHONY : tests/test_uci.i

# target to preprocess a source file
tests/test_uci.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_uci.cpp.i
.PHONY : tests/test_uci.cpp.i

tests/test_uci.s: tests/test_uci.cpp.s
.PHONY : tests/test_uci.s

# target to generate assembly for a file
tests/test_uci.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_uci.cpp.s
.PHONY : tests/test_uci.cpp.s

tests/test_zobrist.o: tests/test_zobrist.cpp.o
.PHONY : tests/test_zobrist.o

# target to build an object file
tests/test_zobrist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_zobrist.cpp.o
.PHONY : tests/test_zobrist.cpp.o

tests/test_zobrist.i: tests/test_zobrist.cpp.i
.PHONY : tests/test_zobrist.i

# target to preprocess a source file
tests/test_zobrist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_zobrist.cpp.i
.PHONY : tests/test_zobrist.cpp.i

tests/test_zobrist.s: tests/test_zobrist.cpp.s
.PHONY : tests/test_zobrist.s

# target to generate assembly for a file
tests/test_zobrist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/test_zobrist.cpp.s
.PHONY : tests/test_zobrist.cpp.s

third_party/fathom/tbprobe.o: third_party/fathom/tbprobe.c.o
.PHONY : third_party/fathom/tbprobe.o

# target to build an object file
third_party/fathom/tbprobe.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/fathom/tbprobe.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/third_party/fathom/tbprobe.c.o
.PHONY : third_party/fathom/tbprobe.c.o

third_party/fathom/tbprobe.i: third_party/fathom/tbprobe.c.i
.PHONY : third_party/fathom/tbprobe.i

# target to preprocess a source file
third_party/fathom/tbprobe.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/fathom/tbprobe.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/third_party/fathom/tbprobe.c.i
.PHONY : third_party/fathom/tbprobe.c.i

third_party/fathom/tbprobe.s: third_party/fathom/tbprobe.c.s
.PHONY : third_party/fathom/tbprobe.s

# target to generate assembly for a file
third_party/fathom/tbprobe.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/fathom/tbprobe.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/third_party/fathom/tbprobe.c.s
.PHONY : third_party/fathom/tbprobe.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... engine"
	@echo "... unit_tests"
	@echo "... nnue_net_data.o"
	@echo "... nnue_net_data.i"
	@echo "... nnue_net_data.s"
	@echo "... src/attacks.o"
	@echo "... src/attacks.i"
	@echo "... src/attacks.s"
	@echo "... src/bitboard.o"
	@echo "... src/bitboard.i"
	@echo "... src/bitboard.s"
	@echo "... src/crash.o"
	@echo "... src/crash.i"
	@echo "... src/crash.s"
	@echo "... src/datagen.o"
	@echo "... src/datagen.i"
	@echo "... src/datagen.s"
	@echo "... src/eval.o"
	@echo "... src/eval.i"
	@echo "... src/eval.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/movegen.o"
	@echo "... src/movegen.i"
	@echo "... src/movegen.s"
	@echo "... src/nnue.o"
	@echo "... src/nnue.i"
	@echo "... src/nnue.s"
	@echo "... src/perft.o"
	@echo "... src/perft.i"
	@echo "... src/perft.s"
	@echo "... src/position.o"
	@echo "... src/position.i"
	@echo "... src/position.s"
	@echo "... src/search.o"
	@echo "... src/search.i"
	@echo "... src/search.s"
	@echo "... src/see.o"
	@echo "... src/see.i"
	@echo "... src/see.s"
	@echo "... src/syzygy.o"
	@echo "... src/syzygy.i"
	@echo "... src/syzygy.s"
	@echo "... src/timeman.o"
	@echo "... src/timeman.i"
	@echo "... src/timeman.s"
	@echo "... src/tt.o"
	@echo "... src/tt.i"
	@echo "... src/tt.s"
	@echo "... src/tune.o"
	@echo "... src/tune.i"
	@echo "... src/tune.s"
	@echo "... src/uci.o"
	@echo "... src/uci.i"
	@echo "... src/uci.s"
	@echo "... src/zobrist.o"
	@echo "... src/zobrist.i"
	@echo "... src/zobrist.s"
	@echo "... tests/test_attacks.o"
	@echo "... tests/test_attacks.i"
	@echo "... tests/test_attacks.s"
	@echo "... tests/test_bitboard.o"
	@echo "... tests/test_bitboard.i"
	@echo "... tests/test_bitboard.s"
	@echo "... tests/test_draw.o"
	@echo "... tests/test_draw.i"
	@echo "... tests/test_draw.s"
	@echo "... tests/test_eval.o"
	@echo "... tests/test_eval.i"
	@echo "... tests/test_eval.s"
	@echo "... tests/test_magic.o"
	@echo "... tests/test_magic.i"
	@echo "... tests/test_magic.s"
	@echo "... tests/test_main.o"
	@echo "... tests/test_main.i"
	@echo "... tests/test_main.s"
	@echo "... tests/test_movegen.o"
	@echo "... tests/test_movegen.i"
	@echo "... tests/test_movegen.s"
	@echo "... tests/test_nnue.o"
	@echo "... tests/test_nnue.i"
	@echo "... tests/test_nnue.s"
	@echo "... tests/test_perft.o"
	@echo "... tests/test_perft.i"
	@echo "... tests/test_perft.s"
	@echo "... tests/test_position.o"
	@echo "... tests/test_position.i"
	@echo "... tests/test_position.s"
	@echo "... tests/test_search.o"
	@echo "... tests/test_search.i"
	@echo "... tests/test_search.s"
	@echo "... tests/test_see.o"
	@echo "... tests/test_see.i"
	@echo "... tests/test_see.s"
	@echo "... tests/test_syzygy.o"
	@echo "... tests/test_syzygy.i"
	@echo "... tests/test_syzygy.s"
	@echo "... tests/test_timeman.o"
	@echo "... tests/test_timeman.i"
	@echo "... tests/test_timeman.s"
	@echo "... tests/test_tt.o"
	@echo "... tests/test_tt.i"
	@echo "... tests/test_tt.s"
	@echo "... tests/test_types.o"
	@echo "... tests/test_types.i"
	@echo "... tests/test_types.s"
	@echo "... tests/test_uci.o"
	@echo "... tests/test_uci.i"
	@echo "... tests/test_uci.s"
	@echo "... tests/test_zobrist.o"
	@echo "... tests/test_zobrist.i"
	@echo "... tests/test_zobrist.s"
	@echo "... third_party/fathom/tbprobe.o"
	@echo "... third_party/fathom/tbprobe.i"
	@echo "... third_party/fathom/tbprobe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /mnt/c/Users/nikod/Documents/uni/chess/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

