#!/usr/bin/env bash
# Data flywheel round 3: SF-relabel the ~62M new self-play positions (extra5 +
# extra5b, generated by the 112M engine) and merge with the 112M corpus -> ~174M.
set -u
K=/home/nikodem/king
RUN=/mnt/c/Users/nikod/Documents/uni/chess/trainer/sf_label_run.sh
echo "[r3] concatenating extra5 + extra5b ..."
cat "$K/nnue_extra5.txt" "$K/nnue_extra5b.txt" > "$K/extra5all.txt"
echo -n "[r3] extra5all lines: "; wc -l < "$K/extra5all.txt"
echo "[r3] SF-relabeling extra5all @ nodes 5000, 22 workers ..."
bash "$RUN" "$K/extra5all.txt" "$K/extra5all_sf.txt" 5000 22
echo "[r3] merging all2_sf (112M) + extra5all_sf -> all3_sf.txt ..."
cat "$K/all2_sf.txt" "$K/extra5all_sf.txt" > "$K/all3_sf.txt"
echo -n "[r3] all3_sf total lines: "; wc -l < "$K/all3_sf.txt"
echo "[r3] DONE -> all3_sf.txt"
