#!/usr/bin/env python3
"""embed_net.py -- generate a C++ source embedding a binary net file.

Usage:  python tools/embed_net.py <input.bin> <output.cpp>

Emits a translation unit defining:
    extern "C" const unsigned char king_nnue_data[];
    extern "C" const unsigned int  king_nnue_data_len;

so the NNUE net is baked into the engine binary (no runtime file needed).
Run by CMake at build time; the output lives in the build tree and is not
committed.
"""
import sys

def main():
    if len(sys.argv) != 3:
        sys.exit("usage: embed_net.py <input.bin> <output.cpp>")
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "rb") as f:
        data = f.read()

    out = []
    out.append("// AUTO-GENERATED by tools/embed_net.py from " + src)
    out.append("// Do not edit, do not commit. Regenerated at build time.")
    out.append('extern "C" const unsigned char king_nnue_data[] = {')
    line = []
    for i, b in enumerate(data):
        line.append("%d," % b)
        if len(line) == 20:
            out.append("".join(line))
            line = []
    if line:
        out.append("".join(line))
    out.append("};")
    out.append('extern "C" const unsigned int king_nnue_data_len = %du;' % len(data))
    out.append("")

    with open(dst, "w", encoding="ascii") as f:
        f.write("\n".join(out))

if __name__ == "__main__":
    main()
